name: Christmas and Brute

on:
  push:
    branches:
      - main

jobs:
    run-brute:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: install pytest
        run: pip install pytest pytest-spec pytest-describe pytest-mock

      - name: run pytest
        run: pytest --spec test_brute.py
    
    run-christmas:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: install pytest
          run: pip install pytest pytest-spec pytest-describe

        - name: run pytest
          run: pytest --spec test_christmas_list.py